export const username = '#username';
export const password = '#login';
export const title = 'h1';
export const logout_option = '.account-signout';
export const admin_menu_sales = '#menu-magento-sales-sales';
export const admin_menu_sales_orders = '.item-sales-order.level-2';
export const admin_data_grid = '.admin__data-grid-wrap'
export const admin_sales_order_grid_cells = '.data-grid-cell-content';
export const action_menu_item = '.action-menu-item';
export const admin_grid_search = '.data-grid-search-control';
export const admin_grid_search_submit = '.data-grid-search-control-wrap .action-submit';
